#!/usr/bin/env swift
// Mechanical export from the approved iOS master. Run on macOS with Swift;
// --check compares generated bytes without updating any resource.
import AppKit
import CryptoKit

let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
let sourceURL = root.appendingPathComponent("ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png")
let source = try Data(contentsOf: sourceURL)
guard let bitmap = NSBitmapImageRep(data: source), let master = bitmap.cgImage,
      master.width == 1024, master.height == 1024 else {
    fatalError("The approved iOS master must be a 1024 × 1024 PNG")
}
let check = CommandLine.arguments.contains("--check")
let space = CGColorSpace(name: CGColorSpace.sRGB)!
var mismatches: [String] = []

func export(_ path: String, _ data: Data) throws {
    let url = root.appendingPathComponent(path)
    if check {
        if (try? Data(contentsOf: url)) != data { mismatches.append(path) }
    } else {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: url, options: .atomic)
    }
}

func canvas(_ size: Int) -> CGContext {
    CGContext(data: nil, width: size, height: size, bitsPerComponent: 8,
              bytesPerRow: size * 4, space: space,
              bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
}

func png(_ context: CGContext) -> Data {
    NSBitmapImageRep(cgImage: context.makeImage()!).representation(using: .png, properties: [:])!
}

func render(_ size: Int, inset: CGFloat = 0, rounded: Bool = false, monochrome: Bool = false) -> Data {
    let context = canvas(size)
    let edge = CGFloat(size)
    if rounded {
        context.addPath(CGPath(roundedRect: CGRect(x: 0, y: 0, width: edge, height: edge),
                               cornerWidth: edge * 0.223, cornerHeight: edge * 0.223, transform: nil))
        context.clip()
    }
    context.interpolationQuality = .high
    context.draw(master, in: CGRect(x: edge * inset, y: edge * inset,
                                   width: edge * (1 - 2 * inset), height: edge * (1 - 2 * inset)))
    if monochrome, let bytes = context.data?.assumingMemoryBound(to: UInt8.self) {
        // Keep the antialiased black silhouette of the approved white-backed
        // master for Android themed icons instead of exposing a solid box.
        for pixel in 0..<(size * size) {
            let offset = pixel * 4
            let alpha = Double(bytes[offset + 3])
            let coverage = max(0, min(alpha, alpha - Double(bytes[offset + 1])))
            bytes[offset] = 0
            bytes[offset + 1] = 0
            bytes[offset + 2] = 0
            bytes[offset + 3] = UInt8(coverage.rounded())
        }
    }
    return png(context)
}

// Preserve iOS geometry and the approved black symbol. Harmony applies
// its launcher mask; Android adaptive icons use the same mark in a 66dp safe area.
try export("harmony-native/AppScope/resources/base/media/app_icon_v3.png", source)
for (density, iconSize, adaptiveSize) in [("mdpi", 48, 108), ("hdpi", 72, 162),
                                        ("xhdpi", 96, 216), ("xxhdpi", 144, 324), ("xxxhdpi", 192, 432)] {
    let base = "android/app/src/main/res/"
    let legacy = render(iconSize, rounded: true)
    try export("\(base)mipmap-\(density)/ic_launcher.png", legacy)
    try export("\(base)mipmap-\(density)/ic_launcher_round.png", legacy)
    let inset: CGFloat = (1 - 66.0 / 108.0) / 2
    try export("\(base)drawable-\(density)/ic_launcher_foreground.png", render(adaptiveSize, inset: inset))
    try export("\(base)drawable-\(density)/ic_launcher_monochrome.png", render(adaptiveSize, inset: inset, monochrome: true))
}
guard try Data(contentsOf: sourceURL) == source else { fatalError("The source master changed during export") }
if !mismatches.isEmpty {
    for path in mismatches { fputs("Outdated icon: \(path)\n", stderr) }
    exit(1)
}
print("\(check ? "Verified" : "Exported") 21 launcher resources; source SHA256 \(SHA256.hash(data: source))")
